server:
  port: 8080

spring:
  application:
    name: payments-service

  datasource:
    url: jdbc:postgresql://db:5432/observability
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: create-drop  # Puede ser: none, validate, update, create, create-drop
      show-sql: true       # Muestra las consultas SQL en consola
      properties:
        hibernate:
          format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
