spring:
  application:
    name: tests
  datasource:
    url: jdbc:h2:file:C:/temp/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect