version: '3.8'

services:
  # Kafka
  kafka:
    image: apache/kafka:latest
    container_name: kafka-broker
    networks:
      - distributed-tracing-net
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  # Jaeger para trazabilidad
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    networks:
      - distributed-tracing-net
    ports:
      - "16686:16686" # the jaeger UI
      #- "4317:4317" # the OpenTelemetry collector grpc
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  # Orders Microservice
  orders-service:
    build: ./orders-service
    container_name: orders-service
    networks:
      - distributed-tracing-net
    ports:
      - "8081:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  # Payments Microservice
  payments-service:
    build: ./payments-service
    container_name: payments-service
    networks:
      - distributed-tracing-net
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

networks:
  distributed-tracing-net:
    driver: bridge